# Terminal
set -g default-terminal "xterm-256color"
set -ag terminal-overrides ",xterm-256color:Tc"
set -g set-clipboard on
set -sg escape-time 10

# Prefix
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

# Vi mode + clipboard
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"

# Splits
unbind %
unbind '"'
bind | split-window -h
bind - split-window -v

# Pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Catppuccin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "slanted"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

run ~/.local/share/tmux/plugins/catppuccin/catppuccin.tmux

set -g status-interval 5
set -g status-left "#{E:@catppuccin_status_session}"
set -g status-right "#[fg=#{@thm_green},bg=#{@thm_surface_0}] #(cd #{pane_current_path} && git rev-parse --abbrev-ref HEAD 2>/dev/null) "
